print("Welcome to the tip calculator.")
bill=float(input("What was the total bill ? $"))
tip = int(input("what percentage tip would you like to give? 10, 12 or 15?"))
person=int(input("how many people to split the bill? "))
bill_per_person=round((bill +((tip/100)*bill))/person,2)
bill_per_person="{:.2f}".format(bill_per_person)
print(f"Each person should pay: ${bill_per_person}")